name: Android Release

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
